### ISSUE TITLE
how do i use it with the version6 of babel

### ISSUE THREAD

**Issue by itlixiaolong** [tc39/proposal-optional-chaining#132]
![image](https://user-images.githubusercontent.com/26212782/72678199-a98d9380-3ade-11ea-920f-e87f8d068443.png)

**Comment by TrySound** [comment]
@itlixiaolong You should upgrade to babel 7.

**Comment by claudepache** [comment]
@itlixiaolong Per https://babeljs.io/blog/2020/01/11/7.8.0, 
Optional chaining is enabled by default in Babel 7.8.0. So you should consider to upgrade...

But this is not the right place to ask questions about Babel. If you need further support, see https://github.com/babel/babel/blob/master/README.md#looking-for-support. 

I’m closing this thread as off-topic.

**Comment by itlixiaolong** [comment]
Thank you for your answers and suggestions
