### ISSUE TITLE
Should `delete a?.b` be allowed or forbidden?

### ISSUE THREAD

**Issue by claudepache** [tc39/proposal-optional-chaining#14]
The right semantics of `delete a?.b` is evident and requires practically zero effort to spec. Should it be allowed or not?

**Comment by ljharb** [comment]
Deletion is strange enough; I'm not sure why we would want conditional deletion. We shouldn't be striving to add optional chaining everywhere it's possible imo; only where it's useful.

**Comment by rattrayalex** [comment]
Agreed with @ljharb . 

`delete a?.b` seems like the kind of thing I would immediately write a linter rule to prevent if I ever saw it in the wild; it sounds like sloppy code for a case that shouldn't be encouraged. Furthermore, if I ever had an inclination to write it, I don't think I would expect it to work (at least, I would check "the docs", but I wouldn't assume either way).

**Comment by jridgewell** [comment]
Babel itself could benefit from optional deletion: https://github.com/babel/babel/blob/28ae47a174f67a8ae6f4527e0a66e88896814170/packages/babel-helper-builder-react-jsx/src/index.js#L66-L69

Not every parser adds the `extra` object to `Node`, and babylon doesn't necessarily need to do it either.

**Comment by ljharb** [comment]
That there exists a use case isn't necessarily a reason to add the feature :-)

**Comment by claudepache** [comment]
Thanks for the use case.

I expect to  _provisionally_ keep the “optional delete” feature when resolving #13 (but this Issue will remain open until a final decision is made).

**Comment by claudepache** [comment]
After careful consideration, I think that `delete a?.b` must be allowed, because:

* it is consistent with `delete a.b` not throwing when `a` evaluates to, say, a String;
* it has a reasonable use case;
* its semantics not confusing.

Or said the other way, forbidding that form, will introduce an inconsistency in the semantics of `delete` (which is very permissive, even in strict mode), will prevent a reasonable use case, and won’t resolve any real issue.

**Comment by claudepache** [comment]
The ongoing refactoring of Issue #20 will imply that optional delete will be implemented even without changing a jot in the current specification of the `delete` operator. Disallowing it would be artificial. So, in absence of strong reason for forbidding, I am closing this issue.

**Comment by caub** [comment]
I don't think `delete` should be supported if assignment is not

```js
const o={}: o?.foo='bar'; o
```
is not supported as I see
