### ISSUE TITLE
Typo (missing the dot operator)

### ISSUE THREAD

**Issue by RinatValiullov** [tc39/proposal-optional-chaining#142]
https://github.com/tc39/proposal-optional-chaining/blob/8461024a040d9c41ec039e2d4291fe2dfda36574/README.md#L58

The following constructs are missing the dot `.` operator:
`a?[b] or a?(b)`

It should be:
`a?.[b] or a?.(b)`

**Comment by claudepache** [comment]
No, because this sentence refers to the languages mentioned in the “Prior Art” section, not to ECMAScript.
