### ISSUE TITLE
Move spec development to the same repository

### ISSUE THREAD

**Issue by littledan** [tc39/proposal-optional-chaining#15]
It seems that the spec here is developed in http://github.com/claudepache/es-optional-chaining . I'm not sure how this happened exactly--it would be useful to have them in the same repository, with the same bug tracker, commits which span both the explainer and spec, etc.

**Comment by claudepache** [comment]
Issue #20 is a major rewrite. I intend to publish the new version implementing #20 on this repo, while keeping the historical, old version on my repo with a obsolescence warning and a forward reference to the up-to-date version.
