### ISSUE TITLE
Similar mechanism for destructuring

### ISSUE THREAD

**Issue by vilic** [tc39/proposal-optional-chaining#19]
Is there any discussion on similar mechanism for destructuring usage? E.g.:

```js
let {foo?: {bia, pia}} = bar;
```

**Comment by gisenberg** [comment]
There was some prior discussion here: https://github.com/tc39/proposal-optional-chaining/issues/6

I'll be talking about destructuring in the context of the optional chaining operator at TC39 this week.

**Comment by vilic** [comment]
@gisenberg Thanks for the reference. Interesting, I though I have searched through the issues...
