### ISSUE TITLE
considering the note

### ISSUE THREAD

**Issue by GrosSacASac** [tc39/proposal-optional-chaining#8]
in the readme, would it be a good idea to use another symbol, other than `?.` ? maybe 
this one `#`

**Comment by ljharb** [comment]
That one is taken by private fields, and doesn't connote "optional" in any way imo.

**Comment by xtuc** [comment]
I agree with @ljharb.

I prefer `a?.b?.c` rather than `a#b#c`. It has a more explicit syntax for optionnal and it is comparable to other languages.

**Comment by Mouvedia** [comment]
`#` is commonly used to denote instance methods.

**Comment by ljharb** [comment]
Swapping `#` for `@` between decorators and private fields (which would have addressed "denote instance methods") was rejected by TC39.

**Comment by claudepache** [comment]
The `?.` token is one of the most commonly used token amongst different languages for that purpose. Why do you want to use another symbol?

**Comment by GrosSacASac** [comment]
I was considering the note

**Comment by gisenberg** [comment]
@GrosSacASac I'm not sure I follow. What note are you referring to, specifically? Or are you asking for one in which an alternate possible syntax is proposed?

**Comment by Mouvedia** [comment]
> Swapping # for @ between decorators and private fields (which would have addressed "denote instance methods") was rejected by TC39.

Well at least it's `object.#a` and not `object#a`.
